#!/bin/bash

npm update
ln -s $PWD/app.js $PWD/pebblejs/src/js/app.js
ln -s $PWD/appinfo.json $PWD/pebblejs/appinfo.json
ln -s $PWD/lib/carwings.js $PWD/pebblejs/src/js/lib/carwings.js
ln -s $PWD/lib/display.js $PWD/pebblejs/src/js/lib/display.js
ln -s $PWD/lib/flow.js $PWD/pebblejs/src/js/lib/flow.js
ln -s $PWD/lib/menu.js $PWD/pebblejs/src/js/lib/menu.js
ln -s $PWD/images $PWD/pebblejs/resources/images
